name: andypbrowne
favicon: null
layout_spectrum: 0.9424919739831239
typography_spectrum: 0.7758408391382545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.24188178940676153
  lightness: 0.43501678854227066
  saturation: 0.03993194526992738
  rhythmicContrast: 0.757771905977279
purpose: []
